- name: install openstack liberty repo for OpenVswitch
  yum: name=centos-release-openstack-liberty state=present

- name: install openvswitch
  yum: name=openvswitch state=present update_cache=yes

- name: Enable openvswitch module
  modprobe:
     name: "openvswitch"
     state: present

- name: Start openvswitch service
  service:
    name: openvswitch
    state: started

- name: configure bridge
  template: src=ifcfg-br.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ krast_bridge_name }} owner=root mode="u=rw,g=r,o=r"
