- name: install openstack liberty repo for OpenVswitch
  yum: name=centos-release-openstack-rocky state=present

- name: install openvswitch
  yum: name=openvswitch state=present update_cache=yes

- name: Enable openvswitch module
  modprobe:
     name: "openvswitch"
     state: present

- name: Start and enable openvswitch service
  service:
     name: openvswitch
     state: started
     enabled: yes
